# 广告联盟 SDK（穿山甲 / 优量汇 / 快手联盟 / 字节）
# ---- 来源：app2smile/rules adsense (a2s_adsense.sgmodule) ----
adsense = type=http-response,pattern=^https:\/\/((api-access\.pangolin-sdk-toutiao|is\.snssdk)\.com\/api\/ad\/union\/sdk\/get_ads|open\.e\.kuaishou\.com\/rest\/e\/v3\/open\/univ$|mi\.gdt\.qq\.com\/gdt_mview\.fcg\?),requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/app2smile/rules/master/js/adsense.js
