# 哔哩哔哩
# ---- 来源：biliad @ddgksf2013/@bm7 (d_biliad.module) ----
^https?:\/\/app\.bilibili\.com\/x\/resource\/ip - reject
^https?:\/\/app\.bilibili\.com\/bilibili\.app\.interface\.v1\.Search\/Default - reject
^https?:\/\/app\.bilibili\.com\/x\/resource\/top\/activity - reject-dict
^https://app.bilibili.com/x/v2/splash/show - reject-dict
^https://app.bilibili.com/x/v2/search/defaultwords - reject-dict
^https?:\/\/api\.bilibili\.com\/x\/vip\/ads\/material\/report - reject-dict
^https://api.bilibili.com/pgc/season/player/cards - reject-dict
^https?:\/\/api\.vc\.bilibili\.com\/search_svr\/v\d\/Search\/recommend_words - reject
^https?:\/\/api\.vc\.bilibili\.com\/topic_svr\/v1\/topic_svr - reject-dict
^https?:\/\/api\.bilibili\.com\/pgc\/season\/app\/related\/recommend\? - reject-dict
^https?:\/\/manga\.bilibili\.com\/twirp\/comic\.v\d\.Comic\/(Flash|ListFlash) - reject-dict
