# 微博 / 微博国际版
# ---- 来源：lalifeier/Shadowrocket 微博 @RuCu6/@zmqcherish (lal_weibo.sgmodule) ----
^https:\/\/api\.weibo\.cn\/2\/(ug\/checkin\/list|push\/daily)\? - reject-dict
^https:\/\/api\.weibo\.cn\/2\/!\/live\/media_homelist\? - reject-dict
^https:\/\/api\.weibo\.cn\/2\/comments\/bullet_screens\? - reject-dict
^https:\/\/api\.weibo\.cn\/2\/photo\/info\? - reject-dict
^https:\/\/api\.weibo\.cn\/2\/statuses\/(container_positive|push_info)\? - reject-dict
^https:\/\/api\.weibo\.cn\/2\/vote\/get_vote_detail\? - reject-dict
^https:\/\/api\.weibo\.cn\/2\/!\/chaohua\/discovery\/home_bottom\/switch\? - reject-dict
^https:\/\/api\.weibo\.cn\/2\/!\/huati\/(discovery_home_bottom_getdotinfo|mobile_discovery_searchchange)\? - reject-dict
^https:\/\/api\.weibo\.cn\/2\/!\/wbox\/\w+\/(home_bottom_modal|interest_category)\? - reject-dict
^https:\/\/api\.weibo\.cn\/2\/search\/container_discover\? - reject-dict
^https:\/\/api\.weibo\.cn\/2\/hot\/hours_spotlight\? - reject-dict
^https:\/\/api\.weibo\.cn\/2\/video\/redpacket\? - reject-dict
^https:\/\/api\.weibo\.cn\/!\/sug\/list\/finderchange\? - reject-dict
^https:\/\/bootrealtime\.uve\.weibo\.com\/v[23]\/ad\/realtime - reject-dict
^https:\/\/sdkapp\.uve\.weibo\.com\/interface\/sdk\/(get-lbs-cell-info\.php|sdkconfig\.php) - reject
^https:\/\/card\.weibo\.com\/article\/m\/aj\/(reward|uvead)\? - reject-dict
^https:\/\/weibo\.com\/ttarticle\/x\/m\/aj\/(reward|uvead)\? - reject-dict

# ---- 来源：WeiboBlock @deezertidal (d_WeiboBlock.sgmodule) ----
