# YouTube（可选模块）
# ---- 来源：YouTubeAd @Maasea (d_YouTubeAd.sgmodule) ----
(^https?:\/\/[\w-]+\.googlevideo\.com\/(?!dclk_video_ads).+?)&ctier=L(&.+?),ctier,(.+) $1$2$3 302
^https?:\/\/[\w-]+\.googlevideo\.com\/(?!(dclk_video_ads|videoplayback\?)).+&oad - reject-200
^https?:\/\/(www|s)\.youtube\.com\/api\/stats\/ads - reject-200
^https?:\/\/(www|s)\.youtube\.com\/(pagead|ptracking) - reject-200
^https?:\/\/s\.youtube\.com\/api\/stats\/qoe\?adcontext - reject-200

# ---- 来源：lalifeier/Shadowrocket YouTube (lal_youtube.sgmodule) ----
^https?:\/\/[\w-]+\.googlevideo\.com\/initplayback.+&oad - reject-200
